### ISSUE TITLE
Add favicons v6 support

### ISSUE THREAD

**Issue by perrin4869** [rejas/gulp-favicons#11]
Hm... I was also wondering if it wouldn't be a good idea to either bring in the `stream` interface from core `favicons` into this module, or go ahead and deprecate this one so as not to cause unnecessary maintenance overhead and/or confusion. @evilebottnawi What do you think?
Thanks!

**Comment by alexander-akait** [comment]
@perrin4869 Agree

**Comment by rejas** [comment]
So what is your favorite way @evilebottnawi ? I am indifferent since I am not using this util in any projects of mine at the moment...

**Comment by perrin4869** [comment]
Maybe deprecate this module is the way to go? It's certainly the simplest, since it won't require to move code over to here and update the setup. But of course I am also indifferent in the end

**Comment by rejas** [comment]
Yeah, I guess that is the more sensible approach...

**Comment by rejas** [comment]
Latest favicon support addded with https://github.com/gulp-community/gulp-favicons/pull/26
