### ISSUE TITLE
favicons v7 upgrade stop generating list of favicons

### ISSUE THREAD

**Issue by peterwcm** [rejas/gulp-favicons#28]
Hi @perrin4869 and @rejas,

Thank you for the recent favicons v7 upgrade changes made in https://github.com/gulp-community/gulp-favicons/pull/26

However, I can't seem to get it working. I pulled the latest `main` branch to my local and ran a `npm install` & `npm test`, I expected the gulp task to generate a list of favicons and the result HTML file but it basically just copied over the src image (logo.png) to the dest folder, see below screenshot. I also tried deleting the existing HTML file and rerunning the gulp task doesn't regenerate it.

<img width="178" alt="image" src="https://user-images.githubusercontent.com/1912260/227792187-d7c5a4f6-e1d8-4162-a98d-89bfd014f0f4.png">

I wonder if this is the correct behaviour with this upgrade? Cheers.

System Information:
macOS: Ventura 13.2.1 (Apple M2 Pro 14" 2023)
node: v18.15.0
npm: 9.5.0

**Comment by perrin4869** [comment]
Thanks! I sent a fix at #29 😄
Can you give it a spin?

**Comment by peterwcm** [comment]
Thanks for the quick fix @perrin4869! I tested it locally and it's working fine. I even tested it with my current setup and there is no regression. Cheers.
