### ISSUE TITLE
Can't create v4 release

### ISSUE THREAD

**Issue by rejas** [rejas/gulp-favicons#30]
Hi @demurgos @yocontra @tracker1 @A-312 

would love to release a v4 on npm (where I think I still have the rights to do so), but cant tag the 4.0.0 here as I dont have the rights for that on github. Could one of you do that for me or get in contact? 
Thanks
V

**Comment by tracker1** [comment]
@rejas I don't think I have that access here either...

**Comment by phated** [comment]
@rejas npm says you have permissions 🤔

**Comment by phated** [comment]
Oh, you said github release. You have write permissions, so you should be able to push a tag. Github says write permissions allow for creating and editing releases: see https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization

**Comment by rejas** [comment]
Thx @phated that did indeed work!
