### ISSUE TITLE
Please remove from npm ASAP

### ISSUE THREAD

**Issue by mmichealjroberts** [rejas/gulp-favicons#9]
This package should be removed from the npm registery because it lacks documentation on how to accurately and effectively use it.

I understand that you are under no obligation to support this gulp package or write documentation, and if you chose not to do those two things then please do not publish to npm.

Thank you.

**Comment by rejas** [comment]
Thanks for the suggestion but I believe that there is sufficient documentation on how to use it in the README and enough usefulness to have it published on npm.
Are you planning on going through all gulp plugins on npm and open tickets for all those that lack documentation in your opinion?

**Comment by mmichealjroberts** [comment]
It lacks good documentation - the README.md doesn't cover half as much as it should. I would advocate for it's removal from npm, yes.

**Comment by rejas** [comment]
I am not sure why you are so interested in this plugin especially, but asking me to remove it "ASAP" just for lacking documentation is quite rude IMO. 

Especially when you dont seem to have interacted with this plugin in any other way before (or opened issues on any other plugin without good documentation). Did you try to use it and were put off by the lack of docs?

If so, would you like to create a PR with some more documentation if you are so keen on it? Creation is better than desctruction IMO. Would surely love to merge it.
